--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-20-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_TABLE
--------------------------------------------------------

  CREATE TABLE "C##TRAVEL"."ADMIN_TABLE" 
   (	"ID" VARCHAR2(30 BYTE), 
	"PWD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TRAVEL.ADMIN_TABLE
SET DEFINE OFF;
Insert into C##TRAVEL.ADMIN_TABLE (ID,PWD) values ('admin','1234');
--------------------------------------------------------
--  DDL for Index SYS_C008358
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TRAVEL"."SYS_C008358" ON "C##TRAVEL"."ADMIN_TABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_TABLE
--------------------------------------------------------

  ALTER TABLE "C##TRAVEL"."ADMIN_TABLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
