--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-20-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "C##TRAVEL"."NOTICE" 
   (	"NOTICE_NO" NUMBER, 
	"TITLE" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(60 BYTE), 
	"NOTICE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TRAVEL.NOTICE
SET DEFINE OFF;
Insert into C##TRAVEL.NOTICE (NOTICE_NO,TITLE,CONTENT,NOTICE_DATE) values (7,'eew','ewq',to_date('23/01/10 02:30:03','RR/MM/DD HH24:MI:SS'));
Insert into C##TRAVEL.NOTICE (NOTICE_NO,TITLE,CONTENT,NOTICE_DATE) values (8,null,'22',to_date('23/01/10 02:58:34','RR/MM/DD HH24:MI:SS'));
Insert into C##TRAVEL.NOTICE (NOTICE_NO,TITLE,CONTENT,NOTICE_DATE) values (4,'호호','33',to_date('23/01/09 23:47:10','RR/MM/DD HH24:MI:SS'));
Insert into C##TRAVEL.NOTICE (NOTICE_NO,TITLE,CONTENT,NOTICE_DATE) values (5,'오늘','좋은',to_date('23/01/09 23:49:17','RR/MM/DD HH24:MI:SS'));
Insert into C##TRAVEL.NOTICE (NOTICE_NO,TITLE,CONTENT,NOTICE_DATE) values (15,'하하','하하',to_date('23/01/10 11:30:00','RR/MM/DD HH24:MI:SS'));
Insert into C##TRAVEL.NOTICE (NOTICE_NO,TITLE,CONTENT,NOTICE_DATE) values (16,'하하','하하',to_date('23/01/10 00:00:00','RR/MM/DD HH24:MI:SS'));
Insert into C##TRAVEL.NOTICE (NOTICE_NO,TITLE,CONTENT,NOTICE_DATE) values (3,'하하','22',to_date('23/01/09 23:43:49','RR/MM/DD HH24:MI:SS'));
Insert into C##TRAVEL.NOTICE (NOTICE_NO,TITLE,CONTENT,NOTICE_DATE) values (10,'ee','wq',to_date('23/01/11 00:09:03','RR/MM/DD HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Index SYS_C008359
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TRAVEL"."SYS_C008359" ON "C##TRAVEL"."NOTICE" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "C##TRAVEL"."NOTICE" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
