--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-20-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_TABLE
--------------------------------------------------------

  CREATE TABLE "C##TRAVEL"."USER_TABLE" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"NAME" VARCHAR2(15 BYTE), 
	"CITIZEN_NUMBER" VARCHAR2(15 BYTE), 
	"AGE" NUMBER, 
	"USER_TEL" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TRAVEL.USER_TABLE
SET DEFINE OFF;
Insert into C##TRAVEL.USER_TABLE (USER_ID,USER_PWD,NAME,CITIZEN_NUMBER,AGE,USER_TEL,EMAIL) values ('abcd1234','1234','kim','941010-1010101',25,'010-1111-2222','abc@gmail.com');
Insert into C##TRAVEL.USER_TABLE (USER_ID,USER_PWD,NAME,CITIZEN_NUMBER,AGE,USER_TEL,EMAIL) values ('abc1d144','9374','hong','761010-1073101',30,'017-1111-2222','blic23@naver.com');
Insert into C##TRAVEL.USER_TABLE (USER_ID,USER_PWD,NAME,CITIZEN_NUMBER,AGE,USER_TEL,EMAIL) values ('gog22','gog232','kang','901013-1033101',20,'010-9292-3221','belo@daum.net');
--------------------------------------------------------
--  DDL for Index SYS_C008357
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TRAVEL"."SYS_C008357" ON "C##TRAVEL"."USER_TABLE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_TABLE
--------------------------------------------------------

  ALTER TABLE "C##TRAVEL"."USER_TABLE" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
